version: '3.9'
services:
  db:
   image: mariadb:10
   restart: always
   environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_PASSWORD=anothersecret
    - MYSQL_USER=snippetbox_user
    - MYSQL_DATABASE=snippetbox_db
   ports:
    - '3306:3306'
   expose:
    - '3306'
   volumes:
     - ./mariadb_data:/var/lib/mysql
volumes:
  db:
   driver: local
